title: Farrel Augusta Dinata
description: A guy who learn about tech everyday
baseurl: ""
url: https://github.com/FarrelAD

theme: cvless

# site settings
taglong: FAD personal
tagshort: FAD personal

# author settings
author:
  name: Farrel Augusta Dinata
  email: fad.farrel@gmail.com
photo: https://avatars.githubusercontent.com/u/140877757?v=4
address: Indonesia

# social media links
social:
  facebook: https://web.facebook.com/farrelad100/
  github: https://github.com/FarrelAD
  instagram: https://www.instagram.com/farrel_rr/
  linkedin: https://www.linkedin.com/in/farrelad/

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
