name: Fully Manual Deploy Web App to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo manually
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git source-code
          cd source-code
          git checkout ${{ github.ref_name }}

      - name: Use pre-installed Node.js manually
        run: |
          echo "Available Node versions:"
          ls /opt/hostedtoolcache/node
          export NODE_DIR=$(ls -d /opt/hostedtoolcache/node/18*/x64 | head -n 1)
          echo "Using Node: $NODE_DIR"
          export PATH=$NODE_DIR/bin:$PATH
          node -v
          npm -v

      - name: Install dependencies
        run: |
          cd source-code
          npm ci

      - name: Build the app
        run: |
          cd source-code
          npm run build

      - name: Prepare gh-pages branch folder
        run: |
          mkdir gh-pages
          cp -r source-code/dist/* gh-pages/
          cd gh-pages
          touch .nojekyll

      - name: Deploy to gh-pages branch
        run: |
          cd gh-pages
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy web app to GitHub Pages"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
